# Generated by Django 4.1.7 on 2023-04-02 04:25

import cctvs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='모델명')),
                ('region', models.CharField(max_length=50, verbose_name='감시 지역')),
                ('description', models.TextField(blank=True, verbose_name='상세 주소 / 추가 설명')),
            ],
            options={
                'verbose_name_plural': 'CCTV 관리',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=cctvs.models.custom_upload_to)),
                ('cctv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='cctvs.cctv', verbose_name='cctv')),
            ],
        ),
    ]
