# Generated by Django 4.1.7 on 2023-03-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctv',
            options={'verbose_name_plural': 'CCTVs'},
        ),
    ]
