# Generated by Django 4.2 on 2023-05-12 20:12

import cctvs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationfile',
            name='file',
            field=models.FileField(upload_to=cctvs.models.custom_upload),
        ),
    ]
