# Generated by Django 4.2 on 2023-05-21 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0002_alter_violationfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violationfile',
            options={'verbose_name_plural': 'CCTV 영상 업로드'},
        ),
        migrations.AlterField(
            model_name='violationfile',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
