# Generated by Django 4.1.7 on 2023-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0002_video_upload_alter_video_cctv'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
