# Generated by Django 4.1.7 on 2023-04-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0003_video_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='file_name',
        ),
    ]
