# Generated by Django 4.2 on 2023-06-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cctvs", "0004_alter_violationfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationfile",
            name="cctv",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="cctvs.cctv",
                verbose_name="CCTV",
            ),
        ),
    ]
