# Generated by Django 4.1.7 on 2023-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0004_rename_video_video_file_rename_name_video_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
