# Generated by Django 4.1.7 on 2023-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0005_alter_video_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.BooleanField(default=False, verbose_name='업로드 여부'),
        ),
    ]
