# Generated by Django 4.2 on 2023-05-05 14:55

import cctvs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctvs', '0006_alter_video_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cctvs.models.custom_upload_to)),
                ('cctv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='cctvs.cctv', verbose_name='CCTV')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
