# Generated by Django 4.1.7 on 2023-03-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        ('cctvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('law', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViolationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_info', to='cctvs.cctv')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_info', to='medias.photo')),
                ('name', models.ManyToManyField(related_name='v_info', to='violations.violation')),
            ],
        ),
    ]
