# Generated by Django 4.1.7 on 2023-03-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'verbose_name_plural': '위반규정 관리'},
        ),
        migrations.AlterModelOptions(
            name='violationinfo',
            options={'verbose_name_plural': '규정 위반 데이터 관리'},
        ),
        migrations.RenameField(
            model_name='violationinfo',
            old_name='name',
            new_name='violations',
        ),
        migrations.AlterField(
            model_name='violationinfo',
            name='img',
            field=models.URLField(max_length=300, verbose_name='이미지 URL'),
        ),
    ]
